# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_create(object):
    def setupUi(self, Form_create):
        Form_create.setObjectName("Form_create")
        Form_create.resize(800, 500)
        Form_create.setMinimumSize(QtCore.QSize(800, 500))
        Form_create.setMaximumSize(QtCore.QSize(800, 500))
        Form_create.setSizeIncrement(QtCore.QSize(1, 0))
        Form_create.setStyleSheet("display: block;\n"
"    color: white;\n"
"    text-align: center;\n"
"    padding: 14px 16px;\n"
"    text-decoration: none;\n"
"background: #454545;")
        self.frame_starting_input = QtWidgets.QFrame(Form_create)
        self.frame_starting_input.setEnabled(True)
        self.frame_starting_input.setGeometry(QtCore.QRect(0, 0, 0, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_starting_input.sizePolicy().hasHeightForWidth())
        self.frame_starting_input.setSizePolicy(sizePolicy)
        self.frame_starting_input.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_starting_input.setMaximumSize(QtCore.QSize(800, 500))
        self.frame_starting_input.setSizeIncrement(QtCore.QSize(800, 500))
        self.frame_starting_input.setBaseSize(QtCore.QSize(26, 1))
        self.frame_starting_input.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_starting_input.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_starting_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_starting_input.setMidLineWidth(0)
        self.frame_starting_input.setObjectName("frame_starting_input")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_starting_input)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 801, 451))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(300, 441))
        self.gridLayoutWidget.setMaximumSize(QtCore.QSize(801, 16777215))
        self.gridLayoutWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(300, 61))
        self.label.setMaximumSize(QtCore.QSize(376, 16777215))
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Btn_randChance = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_randChance.setMinimumSize(QtCore.QSize(0, 45))
        self.Btn_randChance.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Btn_randChance.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_randChance.setStyleSheet("QPushButton#Btn_randChance {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randChance:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randChance:pressed { background: rgb(152,15,0); }")
        self.Btn_randChance.setObjectName("Btn_randChance")
        self.gridLayout.addWidget(self.Btn_randChance, 4, 3, 1, 1)
        self.Input_FormOP = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Input_FormOP.setMinimumSize(QtCore.QSize(200, 45))
        self.Input_FormOP.setMaximumSize(QtCore.QSize(375, 45))
        self.Input_FormOP.setSizeIncrement(QtCore.QSize(0, 0))
        self.Input_FormOP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input_FormOP.setToolTipDuration(3)
        self.Input_FormOP.setStyleSheet("QSpinBox#Input_FormOP {\n"
"    display: inline-block;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    text-decoration: none; \n"
"    user-select: none;\n"
"    padding: .5em 2em;\n"
"    outline: none; \n"
"    border: 2px solid;\n"
"    border-radius: 1px;\n"
"    transition: 0.2s;\n"
"} \n"
"QSpinBox#Input_FormOP:hover { background: rgba(255,255,255,.2); }\n"
"QSpinBox#Input_FormOP:pressed { background: rgb(64,199,129); }")
        self.Input_FormOP.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Input_FormOP.setMinimum(1)
        self.Input_FormOP.setMaximum(16777215)
        self.Input_FormOP.setProperty("value", 5)
        self.Input_FormOP.setObjectName("Input_FormOP")
        self.gridLayout.addWidget(self.Input_FormOP, 2, 2, 1, 1)
        self.Btn_allRand = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_allRand.setMinimumSize(QtCore.QSize(0, 60))
        self.Btn_allRand.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_allRand.setStyleSheet("QPushButton#Btn_allRand {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_allRand:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_allRand:pressed { background: rgb(152,15,0); }")
        self.Btn_allRand.setObjectName("Btn_allRand")
        self.gridLayout.addWidget(self.Btn_allRand, 6, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(300, 61))
        self.label_2.setMaximumSize(QtCore.QSize(376, 16777215))
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.Btn_randCountCommand = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_randCountCommand.setMinimumSize(QtCore.QSize(0, 45))
        self.Btn_randCountCommand.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Btn_randCountCommand.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_randCountCommand.setStyleSheet("QPushButton#Btn_randCountCommand {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randCountCommand:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randCountCommand:pressed { background: rgb(152,15,0); }")
        self.Btn_randCountCommand.setObjectName("Btn_randCountCommand")
        self.gridLayout.addWidget(self.Btn_randCountCommand, 3, 3, 1, 1)
        self.Input_FrequencySB = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Input_FrequencySB.setMinimumSize(QtCore.QSize(200, 45))
        self.Input_FrequencySB.setMaximumSize(QtCore.QSize(375, 45))
        self.Input_FrequencySB.setSizeIncrement(QtCore.QSize(3, 0))
        self.Input_FrequencySB.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input_FrequencySB.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Input_FrequencySB.setToolTipDuration(2)
        self.Input_FrequencySB.setStyleSheet("QSpinBox#Input_FrequencySB {\n"
"    display: inline-block;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    text-decoration: none; \n"
"    user-select: none;\n"
"    padding: .5em 2em;\n"
"    outline: none; \n"
"    border: 2px solid;\n"
"    border-radius: 1px;\n"
"    transition: 0.2s;\n"
"} \n"
"QSpinBox#Input_FrequencySB:hover { background: rgba(255,255,255,.2); }\n"
"QSpinBox#Input_FrequencySB:pressed { background: rgb(64,199,129); }")
        self.Input_FrequencySB.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Input_FrequencySB.setMinimum(1)
        self.Input_FrequencySB.setMaximum(16777215)
        self.Input_FrequencySB.setProperty("value", 233)
        self.Input_FrequencySB.setObjectName("Input_FrequencySB")
        self.gridLayout.addWidget(self.Input_FrequencySB, 1, 2, 1, 1)
        self.Input_CountCommand = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Input_CountCommand.setMinimumSize(QtCore.QSize(200, 45))
        self.Input_CountCommand.setMaximumSize(QtCore.QSize(375, 45))
        self.Input_CountCommand.setSizeIncrement(QtCore.QSize(3, 0))
        self.Input_CountCommand.setBaseSize(QtCore.QSize(0, 0))
        self.Input_CountCommand.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input_CountCommand.setToolTipDuration(4)
        self.Input_CountCommand.setStyleSheet("QSpinBox#Input_CountCommand {\n"
"    display: inline-block;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    text-decoration: none; \n"
"    user-select: none;\n"
"    padding: .5em 2em;\n"
"    outline: none; \n"
"    border: 2px solid;\n"
"    border-radius: 1px;\n"
"    transition: 0.2s;\n"
"} \n"
"QSpinBox#Input_CountCommand:hover { background: rgba(255,255,255,.2); }\n"
"QSpinBox#Input_CountCommand:pressed { background:rgb(64,199,129); }")
        self.Input_CountCommand.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Input_CountCommand.setMinimum(1)
        self.Input_CountCommand.setMaximum(999)
        self.Input_CountCommand.setProperty("value", 1)
        self.Input_CountCommand.setObjectName("Input_CountCommand")
        self.gridLayout.addWidget(self.Input_CountCommand, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(300, 61))
        self.label_3.setMaximumSize(QtCore.QSize(376, 16777215))
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(300, 61))
        self.label_5.setMaximumSize(QtCore.QSize(376, 16777215))
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.Btn_randFrequencySB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_randFrequencySB.setMinimumSize(QtCore.QSize(0, 45))
        self.Btn_randFrequencySB.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Btn_randFrequencySB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_randFrequencySB.setStyleSheet("QPushButton#Btn_randFrequencySB {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randFrequencySB:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randFrequencySB:pressed { background: rgb(152,15,0); }")
        self.Btn_randFrequencySB.setObjectName("Btn_randFrequencySB")
        self.gridLayout.addWidget(self.Btn_randFrequencySB, 1, 3, 1, 1)
        self.Btn_next = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_next.setMinimumSize(QtCore.QSize(200, 60))
        self.Btn_next.setMaximumSize(QtCore.QSize(375, 16777215))
        self.Btn_next.setSizeIncrement(QtCore.QSize(3, 0))
        self.Btn_next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_next.setStyleSheet("QPushButton#Btn_next {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#Btn_next:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_next:pressed { background: rgb(64,199,129); }")
        self.Btn_next.setObjectName("Btn_next")
        self.gridLayout.addWidget(self.Btn_next, 6, 2, 1, 1)
        self.Input_FrequencyMP = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Input_FrequencyMP.setMinimumSize(QtCore.QSize(200, 45))
        self.Input_FrequencyMP.setMaximumSize(QtCore.QSize(376, 45))
        self.Input_FrequencyMP.setSizeIncrement(QtCore.QSize(0, 2))
        self.Input_FrequencyMP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input_FrequencyMP.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Input_FrequencyMP.setToolTipDuration(1)
        self.Input_FrequencyMP.setStyleSheet("QSpinBox#Input_FrequencyMP {\n"
"    display: inline-block;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    text-decoration: none; \n"
"    user-select: none;\n"
"    padding: .5em 2em;\n"
"    outline: none; \n"
"    border: 2px solid;\n"
"    border-radius: 1px;\n"
"    transition: 0.2s;\n"
"} \n"
"QSpinBox#Input_FrequencyMP:hover { background: rgba(255,255,255,.2); }\n"
"QSpinBox#Input_FrequencyMP:pressed { background:rgb(64,199,129); }")
        self.Input_FrequencyMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Input_FrequencyMP.setSpecialValueText("")
        self.Input_FrequencyMP.setAccelerated(False)
        self.Input_FrequencyMP.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.Input_FrequencyMP.setProperty("showGroupSeparator", False)
        self.Input_FrequencyMP.setMinimum(1)
        self.Input_FrequencyMP.setMaximum(16777215)
        self.Input_FrequencyMP.setSingleStep(1)
        self.Input_FrequencyMP.setProperty("value", 700)
        self.Input_FrequencyMP.setObjectName("Input_FrequencyMP")
        self.gridLayout.addWidget(self.Input_FrequencyMP, 0, 2, 1, 1)
        self.Btn_randFormOP = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_randFormOP.setMinimumSize(QtCore.QSize(0, 45))
        self.Btn_randFormOP.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Btn_randFormOP.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_randFormOP.setStyleSheet("QPushButton#Btn_randFormOP {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randFormOP:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randFormOP:pressed { background: rgb(152,15,0); }")
        self.Btn_randFormOP.setObjectName("Btn_randFormOP")
        self.gridLayout.addWidget(self.Btn_randFormOP, 2, 3, 1, 1)
        self.Input_Chance = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Input_Chance.setMinimumSize(QtCore.QSize(200, 45))
        self.Input_Chance.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Input_Chance.setSizeIncrement(QtCore.QSize(3, 0))
        self.Input_Chance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Input_Chance.setToolTipDuration(5)
        self.Input_Chance.setMinimum(1)
        self.Input_Chance.setMaximum(100)
        self.Input_Chance.setSingleStep(1)
        self.Input_Chance.setPageStep(10)
        self.Input_Chance.setProperty("value", 85)
        self.Input_Chance.setSliderPosition(85)
        self.Input_Chance.setOrientation(QtCore.Qt.Horizontal)
        self.Input_Chance.setInvertedAppearance(False)
        self.Input_Chance.setInvertedControls(False)
        self.Input_Chance.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Input_Chance.setObjectName("Input_Chance")
        self.gridLayout.addWidget(self.Input_Chance, 4, 2, 1, 1)
        self.Btn_randFrequencyMP = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_randFrequencyMP.setMinimumSize(QtCore.QSize(0, 45))
        self.Btn_randFrequencyMP.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Btn_randFrequencyMP.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_randFrequencyMP.setStyleSheet("QPushButton#Btn_randFrequencyMP {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randFrequencyMP:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randFrequencyMP:pressed { background: rgb(152,15,0); }")
        self.Btn_randFrequencyMP.setObjectName("Btn_randFrequencyMP")
        self.gridLayout.addWidget(self.Btn_randFrequencyMP, 0, 3, 1, 1)
        self.Btn_back = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_back.setMinimumSize(QtCore.QSize(300, 60))
        self.Btn_back.setMaximumSize(QtCore.QSize(376, 16777215))
        self.Btn_back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_back.setStyleSheet("QPushButton#Btn_back {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#Btn_back:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_back:pressed { background: white; }")
        self.Btn_back.setObjectName("Btn_back")
        self.gridLayout.addWidget(self.Btn_back, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_starting_input)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 800, 60))
        self.label_4.setMinimumSize(QtCore.QSize(800, 60))
        self.label_4.setMaximumSize(QtCore.QSize(800, 60))
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.frame_second_input = QtWidgets.QFrame(Form_create)
        self.frame_second_input.setGeometry(QtCore.QRect(0, 0, 0, 500))
        self.frame_second_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_second_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_second_input.setObjectName("frame_second_input")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_second_input)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_tacts_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_2.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_2.setFont(font)
        self.input_tacts_2.setFrame(True)
        self.input_tacts_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_2.setProperty("value", 1)
        self.input_tacts_2.setObjectName("input_tacts_2")
        self.horizontalLayout_3.addWidget(self.input_tacts_2)
        self.input_cache_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_2.setObjectName("input_cache_2")
        self.input_cache_2.addItem("")
        self.input_cache_2.addItem("")
        self.horizontalLayout_3.addWidget(self.input_cache_2)
        self.input_object_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_2.setObjectName("input_object_2")
        self.input_object_2.addItem("")
        self.input_object_2.addItem("")
        self.horizontalLayout_3.addWidget(self.input_object_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_tacts_1 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_1.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_1.setFont(font)
        self.input_tacts_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_1.setProperty("value", 1)
        self.input_tacts_1.setObjectName("input_tacts_1")
        self.horizontalLayout.addWidget(self.input_tacts_1)
        self.input_cache_1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_1.setObjectName("input_cache_1")
        self.input_cache_1.addItem("")
        self.input_cache_1.addItem("")
        self.horizontalLayout.addWidget(self.input_cache_1)
        self.input_object_1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_1.setObjectName("input_object_1")
        self.input_object_1.addItem("")
        self.input_object_1.addItem("")
        self.horizontalLayout.addWidget(self.input_object_1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_tacts_4 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_4.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_4.setFont(font)
        self.input_tacts_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_4.setProperty("value", 1)
        self.input_tacts_4.setObjectName("input_tacts_4")
        self.horizontalLayout_5.addWidget(self.input_tacts_4)
        self.input_cache_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_4.setObjectName("input_cache_4")
        self.input_cache_4.addItem("")
        self.input_cache_4.addItem("")
        self.horizontalLayout_5.addWidget(self.input_cache_4)
        self.input_object_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_4.setObjectName("input_object_4")
        self.input_object_4.addItem("")
        self.input_object_4.addItem("")
        self.horizontalLayout_5.addWidget(self.input_object_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.input_tacts_6 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_6.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_6.setFont(font)
        self.input_tacts_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_6.setProperty("value", 1)
        self.input_tacts_6.setObjectName("input_tacts_6")
        self.horizontalLayout_8.addWidget(self.input_tacts_6)
        self.input_cache_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_6.setObjectName("input_cache_6")
        self.input_cache_6.addItem("")
        self.input_cache_6.addItem("")
        self.horizontalLayout_8.addWidget(self.input_cache_6)
        self.input_object_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_6.setObjectName("input_object_6")
        self.input_object_6.addItem("")
        self.input_object_6.addItem("")
        self.horizontalLayout_8.addWidget(self.input_object_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_tacts_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_3.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_3.setFont(font)
        self.input_tacts_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_3.setProperty("value", 1)
        self.input_tacts_3.setObjectName("input_tacts_3")
        self.horizontalLayout_4.addWidget(self.input_tacts_3)
        self.input_cache_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_3.setObjectName("input_cache_3")
        self.input_cache_3.addItem("")
        self.input_cache_3.addItem("")
        self.horizontalLayout_4.addWidget(self.input_cache_3)
        self.input_object_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_3.setObjectName("input_object_3")
        self.input_object_3.addItem("")
        self.input_object_3.addItem("")
        self.horizontalLayout_4.addWidget(self.input_object_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.Btn_back_to_starter = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Btn_back_to_starter.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_back_to_starter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_back_to_starter.setStyleSheet("QPushButton#Btn_back {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#Btn_back:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_back:pressed { background: white; }")
        self.Btn_back_to_starter.setObjectName("Btn_back_to_starter")
        self.gridLayout_2.addWidget(self.Btn_back_to_starter, 6, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.input_tacts_8 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_8.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_8.setFont(font)
        self.input_tacts_8.setMouseTracking(False)
        self.input_tacts_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_8.setProperty("value", 1)
        self.input_tacts_8.setObjectName("input_tacts_8")
        self.horizontalLayout_13.addWidget(self.input_tacts_8)
        self.input_cache_8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_8.setObjectName("input_cache_8")
        self.input_cache_8.addItem("")
        self.input_cache_8.addItem("")
        self.horizontalLayout_13.addWidget(self.input_cache_8)
        self.input_object_8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_8.setObjectName("input_object_8")
        self.input_object_8.addItem("")
        self.input_object_8.addItem("")
        self.horizontalLayout_13.addWidget(self.input_object_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 4, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Btn_radomFill = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Btn_radomFill.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_radomFill.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_radomFill.setStyleSheet("QPushButton#Btn_randChance {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#Btn_randChance:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_randChance:pressed { background: rgb(152,15,0); }")
        self.Btn_radomFill.setObjectName("Btn_radomFill")
        self.horizontalLayout_18.addWidget(self.Btn_radomFill)
        self.Btn_next_to_new_window = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Btn_next_to_new_window.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_next_to_new_window.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_next_to_new_window.setStyleSheet("QPushButton#Btn_next {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#Btn_next:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#Btn_next:pressed { background: rgb(64,199,129); }")
        self.Btn_next_to_new_window.setObjectName("Btn_next_to_new_window")
        self.horizontalLayout_18.addWidget(self.Btn_next_to_new_window)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 6, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.input_tacts_5 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_5.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_5.setFont(font)
        self.input_tacts_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_5.setProperty("value", 1)
        self.input_tacts_5.setObjectName("input_tacts_5")
        self.horizontalLayout_7.addWidget(self.input_tacts_5)
        self.input_cache_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_5.setObjectName("input_cache_5")
        self.input_cache_5.addItem("")
        self.input_cache_5.addItem("")
        self.horizontalLayout_7.addWidget(self.input_cache_5)
        self.input_object_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_5.setObjectName("input_object_5")
        self.input_object_5.addItem("")
        self.input_object_5.addItem("")
        self.horizontalLayout_7.addWidget(self.input_object_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setMaximumSize(QtCore.QSize(388, 45))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        self.label_CountFill = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_CountFill.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_CountFill.setObjectName("label_CountFill")
        self.horizontalLayout_17.addWidget(self.label_CountFill)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.input_tacts_10 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_10.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_10.setFont(font)
        self.input_tacts_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_10.setProperty("value", 1)
        self.input_tacts_10.setObjectName("input_tacts_10")
        self.horizontalLayout_15.addWidget(self.input_tacts_10)
        self.input_cache_10 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_10.setObjectName("input_cache_10")
        self.input_cache_10.addItem("")
        self.input_cache_10.addItem("")
        self.horizontalLayout_15.addWidget(self.input_cache_10)
        self.input_object_10 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_10.setObjectName("input_object_10")
        self.input_object_10.addItem("")
        self.input_object_10.addItem("")
        self.horizontalLayout_15.addWidget(self.input_object_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 5, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.input_tacts_7 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_7.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_7.setFont(font)
        self.input_tacts_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_7.setProperty("value", 1)
        self.input_tacts_7.setObjectName("input_tacts_7")
        self.horizontalLayout_12.addWidget(self.input_tacts_7)
        self.input_cache_7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_7.setObjectName("input_cache_7")
        self.input_cache_7.addItem("")
        self.input_cache_7.addItem("")
        self.horizontalLayout_12.addWidget(self.input_cache_7)
        self.input_object_7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_7.setObjectName("input_object_7")
        self.input_object_7.addItem("")
        self.input_object_7.addItem("")
        self.horizontalLayout_12.addWidget(self.input_object_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.input_tacts_9 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_tacts_9.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(6)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.input_tacts_9.setFont(font)
        self.input_tacts_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.input_tacts_9.setProperty("value", 1)
        self.input_tacts_9.setObjectName("input_tacts_9")
        self.horizontalLayout_16.addWidget(self.input_tacts_9)
        self.input_cache_9 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_cache_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_cache_9.setObjectName("input_cache_9")
        self.input_cache_9.addItem("")
        self.input_cache_9.addItem("")
        self.horizontalLayout_16.addWidget(self.input_cache_9)
        self.input_object_9 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.input_object_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_object_9.setObjectName("input_object_9")
        self.input_object_9.addItem("")
        self.input_object_9.addItem("")
        self.horizontalLayout_16.addWidget(self.input_object_9)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 5, 0, 1, 1)

        self.retranslateUi(Form_create)
        QtCore.QMetaObject.connectSlotsByName(Form_create)

    def retranslateUi(self, Form_create):
        _translate = QtCore.QCoreApplication.translate
        Form_create.setWindowTitle(_translate("Form_create", "Лабораторная работа №1| Создание"))
        self.label.setText(_translate("Form_create", "<html><head/><body><p>Введите частоту МП:</p></body></html>"))
        self.Btn_randChance.setToolTip(_translate("Form_create", "<html><head/><body><p>выбирает случайно вероятность попадания в КЭШ МП</p></body></html>"))
        self.Btn_randChance.setWhatsThis(_translate("Form_create", "<html><head/><body><p>выбирает случайно вероятность попадания в КЭШ МП</p></body></html>"))
        self.Btn_randChance.setText(_translate("Form_create", "RAND"))
        self.Input_FormOP.setToolTip(_translate("Form_create", "<html><head/><body><p>сокращённая формула оперативной памяти типа XX-1-1-1, XX это введённые цифры </p></body></html>"))
        self.Input_FormOP.setWhatsThis(_translate("Form_create", "<html><head/><body><p>сокращённая формула оперативной памяти типа XX-1-1-1, XX это введённые цифры </p></body></html>"))
        self.Btn_allRand.setToolTip(_translate("Form_create", "<html><head/><body><p>Случайно выбирает значения всех пунктов</p></body></html>"))
        self.Btn_allRand.setWhatsThis(_translate("Form_create", "<html><head/><body><p>Случайно выбирает значения всех пунктов</p></body></html>"))
        self.Btn_allRand.setText(_translate("Form_create", "All RAND"))
        self.label_2.setText(_translate("Form_create", "<html><head/><body><p>Введите частоту СШ:</p></body></html>"))
        self.Btn_randCountCommand.setToolTip(_translate("Form_create", "<html><head/><body><p>выбирает случайное колличество комманд</p></body></html>"))
        self.Btn_randCountCommand.setWhatsThis(_translate("Form_create", "<html><head/><body><p>выбирает случайное колличество комманд</p></body></html>"))
        self.Btn_randCountCommand.setText(_translate("Form_create", "RAND"))
        self.Input_FrequencySB.setToolTip(_translate("Form_create", "<html><head/><body><p>частота системной шины</p></body></html>"))
        self.Input_FrequencySB.setWhatsThis(_translate("Form_create", "<html><head/><body><p>частота системной шины</p></body></html>"))
        self.Input_FrequencySB.setSuffix(_translate("Form_create", " мГЦ"))
        self.Input_CountCommand.setToolTip(_translate("Form_create", "<html><head/><body><p>Колличество комманд выполнения</p></body></html>"))
        self.Input_CountCommand.setWhatsThis(_translate("Form_create", "<html><head/><body><p>Колличество комманд выполнения</p></body></html>"))
        self.Input_CountCommand.setSuffix(_translate("Form_create", " шт."))
        self.label_6.setText(_translate("Form_create", "<html><head/><body><p align=\"justify\">Вероятность попадания в КЭШ МП:</p></body></html>"))
        self.label_3.setText(_translate("Form_create", "<html><head/><body><p>Введите форму ОП:</p></body></html>"))
        self.label_5.setText(_translate("Form_create", "<html><head/><body><p>Введите кол-во команд:</p></body></html>"))
        self.Btn_randFrequencySB.setToolTip(_translate("Form_create", "<html><head/><body><p>выбирает случайную частоту системной шины</p></body></html>"))
        self.Btn_randFrequencySB.setWhatsThis(_translate("Form_create", "<html><head/><body><p>выбирает случайную частоту системной шины</p></body></html>"))
        self.Btn_randFrequencySB.setText(_translate("Form_create", "RAND"))
        self.Btn_next.setToolTip(_translate("Form_create", "<html><head/><body><p>кнопка позволяет перейти к следующей стадии запонения данных</p></body></html>"))
        self.Btn_next.setWhatsThis(_translate("Form_create", "кнопка позволяет перейти к следующей стадии запонения данных"))
        self.Btn_next.setText(_translate("Form_create", "Далее"))
        self.Input_FrequencyMP.setToolTip(_translate("Form_create", "<html><head/><body><p>частота микропроцессора</p></body></html>"))
        self.Input_FrequencyMP.setWhatsThis(_translate("Form_create", "<html><head/><body><p>частота микропроцессора</p></body></html>"))
        self.Input_FrequencyMP.setSuffix(_translate("Form_create", " мГЦ"))
        self.Btn_randFormOP.setToolTip(_translate("Form_create", "<html><head/><body><p>выбирает случайно сокращённую формулу  </p></body></html>"))
        self.Btn_randFormOP.setWhatsThis(_translate("Form_create", "<html><head/><body><p>выбирает случайно сокращённую формулу  </p></body></html>"))
        self.Btn_randFormOP.setText(_translate("Form_create", "RAND"))
        self.Input_Chance.setToolTip(_translate("Form_create", "<html><head/><body><p>вероятность попадания в КЭШ микропроцессора. Измеряется от 1% до 100%</p></body></html>"))
        self.Btn_randFrequencyMP.setToolTip(_translate("Form_create", "<html><head/><body><p>выбирает случайную частоту микропроцессора</p></body></html>"))
        self.Btn_randFrequencyMP.setWhatsThis(_translate("Form_create", "<html><head/><body><p>выбирает случайную частоту микропроцессора</p></body></html>"))
        self.Btn_randFrequencyMP.setText(_translate("Form_create", "RAND"))
        self.Btn_back.setToolTip(_translate("Form_create", "<html><head/><body><p>кнопка позволяет вернутья в главное меню</p></body></html>"))
        self.Btn_back.setWhatsThis(_translate("Form_create", "<html><head/><body><p>кнопка позволяет вернутья в главное меню</p></body></html>"))
        self.Btn_back.setText(_translate("Form_create", "Вернуться"))
        self.label_4.setText(_translate("Form_create", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Заполните данные</span></p></body></html>"))
        self.input_tacts_2.setSuffix(_translate("Form_create", " т."))
        self.input_cache_2.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_2.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_2.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_2.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_1.setSuffix(_translate("Form_create", " т."))
        self.input_cache_1.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_1.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_1.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_1.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_4.setSuffix(_translate("Form_create", " т."))
        self.input_cache_4.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_4.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_4.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_4.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_6.setSuffix(_translate("Form_create", " т."))
        self.input_cache_6.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_6.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_6.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_6.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_3.setSuffix(_translate("Form_create", " т."))
        self.input_cache_3.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_3.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_3.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_3.setItemText(1, _translate("Form_create", "__;"))
        self.Btn_back_to_starter.setText(_translate("Form_create", "Назад"))
        self.input_tacts_8.setSuffix(_translate("Form_create", " т."))
        self.input_cache_8.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_8.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_8.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_8.setItemText(1, _translate("Form_create", "__;"))
        self.Btn_radomFill.setText(_translate("Form_create", "RANDOM"))
        self.Btn_next_to_new_window.setText(_translate("Form_create", "Далее"))
        self.input_tacts_5.setSuffix(_translate("Form_create", " т."))
        self.input_cache_5.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_5.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_5.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_5.setItemText(1, _translate("Form_create", "__;"))
        self.label_7.setText(_translate("Form_create", "Заполните команды"))
        self.label_8.setText(_translate("Form_create", "Заполнено"))
        self.label_CountFill.setText(_translate("Form_create", "0"))
        self.input_tacts_10.setSuffix(_translate("Form_create", " т."))
        self.input_cache_10.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_10.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_10.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_10.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_7.setSuffix(_translate("Form_create", " т."))
        self.input_cache_7.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_7.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_7.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_7.setItemText(1, _translate("Form_create", "__;"))
        self.input_tacts_9.setSuffix(_translate("Form_create", " т."))
        self.input_cache_9.setItemText(0, _translate("Form_create", "(КЭШ,"))
        self.input_cache_9.setItemText(1, _translate("Form_create", "(Н.К.,"))
        self.input_object_9.setItemText(0, _translate("Form_create", "У.О.);"))
        self.input_object_9.setItemText(1, _translate("Form_create", "__;"))
