# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_login.sizePolicy().hasHeightForWidth())
        Form_login.setSizePolicy(sizePolicy)
        Form_login.setMinimumSize(QtCore.QSize(400, 500))
        Form_login.setMaximumSize(QtCore.QSize(400, 500))
        Form_login.setBaseSize(QtCore.QSize(400, 500))
        
        self.splitter_button = QtWidgets.QSplitter(Form_login)
        self.splitter_button.setGeometry(QtCore.QRect(0, 300, 400, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_button.sizePolicy().hasHeightForWidth())
        self.splitter_button.setSizePolicy(sizePolicy)
        self.splitter_button.setMinimumSize(QtCore.QSize(400, 200))
        self.splitter_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.splitter_button.setBaseSize(QtCore.QSize(0, 0))
        self.splitter_button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.splitter_button.setToolTipDuration(0)
        self.splitter_button.setStyleSheet("background: #454545\n"
                                           "")
        self.splitter_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_button.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_button.setOrientation(QtCore.Qt.Vertical)
        self.splitter_button.setOpaqueResize(True)
        self.splitter_button.setHandleWidth(10)
        self.splitter_button.setObjectName("splitter_button")
        
        self.widget = QtWidgets.QWidget(self.splitter_button)
        self.widget.setObjectName("widget")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(25, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.Button_Create = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Create.sizePolicy().hasHeightForWidth())
        self.Button_Create.setSizePolicy(sizePolicy)
        self.Button_Create.setMinimumSize(QtCore.QSize(350, 70))
        self.Button_Create.setMaximumSize(QtCore.QSize(350, 70))
        self.Button_Create.setBaseSize(QtCore.QSize(80, 16))
        self.Button_Create.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Button_Create.setToolTipDuration(0)
        self.Button_Create.setStyleSheet("QPushButton#Button_Create {\n"
                                         "  display: inline-block;\n"
                                         "  color: white;\n"
                                         "  font-weight: 700;\n"
                                         "  text-decoration: none;\n"
                                         "  user-select: none;\n"
                                         "  padding: .5em 2em;\n"
                                         "  outline: none;\n"
                                         "  border: 2px solid;\n"
                                         "  border-radius: 1px;\n"
                                         "  transition: 0.2s;\n"
                                         "} \n"
                                         "QPushButton#Button_Create:hover { background: rgba(255,255,255,.2); }\n"
                                         "QPushButton#Button_Create:pressed { background: white; }")
        self.Button_Create.setAutoRepeatInterval(100)
        self.Button_Create.setFlat(False)
        self.Button_Create.setObjectName("Button_Create")
        
        self.verticalLayout_2.addWidget(self.Button_Create)
        
        
        self.Button_View = QtWidgets.QPushButton(self.widget)
        self.Button_View.setMinimumSize(QtCore.QSize(350, 70))
        self.Button_View.setMaximumSize(QtCore.QSize(350, 70))
        self.Button_View.setToolTipDuration(1)
        self.Button_View.setStyleSheet("QPushButton#Button_View {\n"
                                       "  display: inline-block;\n"
                                       "  color: white;\n"
                                       "  font-weight: 700;\n"
                                       "  text-decoration: none;\n"
                                       "  user-select: none;\n"
                                       "  padding: .5em 2em;\n"
                                       "  outline: none;\n"
                                       "  border: 2px solid;\n"
                                       "  border-radius: 1px;\n"
                                       "  transition: 0.2s;\n"
                                       "} \n"
                                       "\n"
                                       "QPushButton#Button_View:hover { background: rgba(255,255,255,.2); }\n"
                                       "QPushButton#Button_View:pressed { background: rgb(64,199,129); }")
        self.Button_View.setObjectName("Button_View")
        self.verticalLayout_2.addWidget(self.Button_View)
        self.splitter_labels = QtWidgets.QSplitter(Form_login)
        self.splitter_labels.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.splitter_labels.setMinimumSize(QtCore.QSize(400, 190))
        self.splitter_labels.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.splitter_labels.setBaseSize(QtCore.QSize(0, 0))
        self.splitter_labels.setStyleSheet("background: #454545\n"
                                           "")
        self.splitter_labels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_labels.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_labels.setOrientation(QtCore.Qt.Vertical)
        self.splitter_labels.setHandleWidth(18)
        self.splitter_labels.setObjectName("splitter_labels")
        self.label_up = QtWidgets.QLabel(self.splitter_labels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_up.sizePolicy().hasHeightForWidth())
        self.label_up.setSizePolicy(sizePolicy)
        self.label_up.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_up.setFont(font)
        self.label_up.setStyleSheet("body{list-style-type: none;\n"
                                    "    margin: 0;\n"
                                    "    padding: 0;\n"
                                    "    overflow: hidden;\n"
                                    "    background-color: #333;\n"
                                    "}\n"
                                    "QLabel#label_up{\n"
                                    "    display: block;\n"
                                    "    color: white;\n"
                                    "    text-align: center;\n"
                                    "    padding: 14px 16px;\n"
                                    "    text-decoration: none;\n"
                                    "}\n"
                                    "QLabel#label_down{\n"
                                    "    display: block;\n"
                                    "    color: white;\n"
                                    "    text-align: center;\n"
                                    "    padding: 1px 1px;\n"
                                    "    text-decoration: none;\n"
                                    "}")
        self.label_up.setTextFormat(QtCore.Qt.PlainText)
        self.label_up.setObjectName("label_up")
        self.label_down = QtWidgets.QLabel(self.splitter_labels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_down.sizePolicy().hasHeightForWidth())
        self.label_down.setSizePolicy(sizePolicy)
        self.label_down.setMinimumSize(QtCore.QSize(0, 0))
        self.label_down.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.label_down.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_down.setFont(font)
        self.label_down.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_down.setStyleSheet("body{list-style-type: none;\n"
                                      "    margin: 0;\n"
                                      "    padding: 0;\n"
                                      "    overflow: hidden;\n"
                                      "    background-color: #333;\n"
                                      "}\n"
                                      "QLabel#label_up{\n"
                                      "    display: block;\n"
                                      "    color: white;\n"
                                      "    text-align: center;\n"
                                      "    padding: 14px 16px;\n"
                                      "    text-decoration: none;\n"
                                      "}\n"
                                      "QLabel#label_down{\n"
                                      "    display: block;\n"
                                      "    color: rgb(197, 197, 197);\n"
                                      "    text-align: center;\n"
                                      "    padding: 1px 1px;\n"
                                      "    text-decoration: none;\n"
                                      "}")
        self.label_down.setLineWidth(0)
        self.label_down.setTextFormat(QtCore.Qt.RichText)
        self.label_down.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_down.setObjectName("label_down")

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Лабораторная работа №1"))
        self.Button_Create.setText(_translate("Form_login", "Создать"))
        self.Button_View.setText(_translate("Form_login", "Отобразить"))
        self.label_up.setText(_translate("Form_login", "Лабораторная работа №1"))
        self.label_down.setText(_translate("Form_login",
                                           "<html><head/><body><p>Выполнила группа ФИТУ 2-5б.</p><p>- Морозов Р.</p><p>- Католенец Д.</p><p>- Кобыленко Т.</p><p>- Скребнев Л.</p></body></html>"))
